Documentation need to be updated for Admin command to apply deduplication at namespace:
bin/pulsar-admin namespaces set-deduplication \
  persistent://public/default/topic-1 \
  --enable # or just -e

should be

bin/pulsar-admin namespaces set-deduplication \
 public/default \
  --enable # or just -e

How can we reproduce the issue

Running the below statement will result in

java.lang.IllegalArgumentException: Invalid namespace format. namespace: persistent://public/default/topic-1

**Pulsar version**: 2.0-rc1