add pulsar-client-messagecrypto-bc into pulsar-client module (#7447)
Fixes #6834

### Motivation

`MessageCryptoBc` implements the interface of `MessageCrypto`. while `pulsar-client` did a shade to`ByteBuf`, and caused the method parameter changed from `org.apache.pulsar.shade.io.netty.buffer.ByteBuf` to `io.netty.buffer.ByteBuf` and will cause error of:
```
Caused by: java.lang.NoSuchMethodError: 'org.apache.pulsar.shade.io.netty.buffer.ByteBuf org.apache.pulsar.client.api.MessageCrypto.encrypt(java.util.Set, org.apache.pulsar.client.api.CryptoKeyReader, java.util.function.Supplier, org.apache.pulsar.shade.io.netty.buffer.ByteBuf)
```

### Modifications

add pulsar-client-messagecrypto-bc into pulsar-client dependency to avoid method-not-found issue.