Fix peek message failure when broker entry metadata is enabled (#10924)
### Motivation

When broker entry metadata is enabled, using pulsar-admin to peek messages will fail with

```
[pulsar-web-29-16] ERROR org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [null] Failed to peek message at position 1 from persistent://prop/ns-abc/topic-b604aad8ea8010af my-sub
java.lang.IllegalArgumentException: Invalid unknonwn tag type: 6
	at org.apache.pulsar.common.api.proto.LightProtoCodec.skipUnknownField(LightProtoCodec.java:270) ~[classes/:?]
	at org.apache.pulsar.common.api.proto.MessageMetadata.parseFrom(MessageMetadata.java:1370) ~[classes/:?]
	at org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:426) ~[classes/:?]
```

### Modifications

Skip the broker entry metadata if exists in `generateResponseWithEntry` and add the test to verify it.

(cherry picked from commit 7603a9d9fc3d592318aab36b4701bff4a0bd6928)