[CI] Fix Tune Runner VM memory.swappiness no such file or directory
Failed CI: https://github.com/apache/pulsar/runs/4501006108?check_suite_focus=true#step:3:1

### Motivation
The Tune Runner VM is flaky.

Sometimes, the parent directory of memory.swappiness can't find, we should check it first.
```
Run if [[ "$OSTYPE" == "linux-gnu"* ]]; then
10.1.0.235	fv-az198-145.gjkxsqtjg41etoza45cw35jkyb.bx.internal.cloudapp.net fv-az198-145
1
tee: /sys/fs/cgroup/memory/system.slice/snap-snapd-13640.mount/memory.swappiness: No such file or directory
Error: Process completed with exit code 1.
```
### Modifications
Add a check of the parent directory of memory.swappiness

(cherry picked from commit 26ac049997bf10d82c344e7db77f503740280d82)