Fix issue with duplicate classes
Error: Exception in thread "main" java.io.IOException: Error while analyzing /home/runner/.m2/repository/org/apache/pulsar/pulsar-io-kafka/2.12.0-SNAPSHOT/pulsar-io-kafka-2.12.0-SNAPSHOT.jar@META-INF/bundled-dependencies/bcprov-ext-jdk15on-1.69.jar@META-INF/versions/15/org/bouncycastle/jcajce/provider/asymmetric/edec/KeyFactorySpi$Ed25519.class with JaCoCo 0.8.8.202204050719/5dcf34a.
Caused by: java.lang.IllegalStateException: Can't add different class with same name: org/bouncycastle/jcajce/provider/asymmetric/edec/KeyFactorySpi$Ed25519