[Functions]Support protobuf schema for pulsar function (#11709)
### Motivation

Some users have encountered the following exception when using the protobuf schema, so add the relevant dependencies to the instance:

```
ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - Sink open produced uncaught exception:
java.lang.IllegalArgumentException: com.google.protobuf.GeneratedMessageV3 is not assignable from bold.proto.PersonOuterClass$Person
	at org.apache.pulsar.client.impl.schema.ProtobufSchema.of(ProtobufSchema.java:110) ~
```

### Modifications

* Add the relevant dependencies to the instance

### Verifying this change

- [x] Make sure that the change passes the CI checks.

(cherry picked from commit f893c08ae5e356115cdaaa931982807174929f73)