[Tests] Fix OutOfMemoryError and NoClassDefFoundErrors in tests (#15911)
Fixes #15689
Fixes #15793
Fixes #15897

### Motivation

`PulsarByteBufAllocator.DEFAULT` instance was replaced in BatchMessageContainerImplTest, but never restored. This caused strange issues in many unit tests. OutOfMemoryError and NoClassDefFoundErrors  were most likely caused by the BatchMessageContainerImplTest.

### Modifications

Fix the problems in BatchMessageContainerImplTest and reset the state after the test completes.

### Additional context

The flaky test was introduced by #12170 which has been cherry-picked to branch-2.8, branch-2.9 and included also in branch-2.10 .

(cherry picked from commit ef1e0aa73592b4a81bd89a43628096a839b0bc26)
(cherry picked from commit 3f3d4525c495e3da3b98b6929613761f30871a52)