Upgrade commons-cli to 1.5.0
- commons-cli 1.3+ is required by Zookeeper 3.7.0+
  - https://github.com/apache/zookeeper/commit/492fd79b
  - commons-cli versions <1.3 fail with error:
    java.lang.NoClassDefFoundError: org/apache/commons/cli/DefaultParser