Fix NoClassDefFoundError when running pulsar cli tools in development directory
Fixes #10802

- when running pulsar cli tools in a docker container, the cached
  distribution/server/target/classpath.txt must be removed since it
  contains absolute paths

- the generation of distribution/server/target/classpath.txt was invalid
  in the cli scripts. "mvn -pl distribution/server generate-sources"
  should be used to create the file.