[Broker] Fix compilation error related to SystemTopicClient (#14774)
### Motivation

master branch is broken. It broke after merging #12025.


Compiling code fails with this error:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.9.0:compile (default-compile) on project pulsar-broker: Compilation failure
Error:  /home/runner/work/pulsar/pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:[1528,36] cannot find symbol
Error:    symbol:   variable SystemTopicClient
Error:    location: class org.apache.pulsar.broker.service.BrokerService
Error:  -> [Help 1]
Error:  
```

#14671 had removed the `SystemTopicClient.isSystemTopic` method.


### Modifications

replace `SystemTopicClient.isSystemType` with `isSystemTopic` since BrokerService contains a method called `isSystemTopic`.