catch_throwable (#7221)
Motivation
Currently, pulsar only catch exception when BrokerStarter.start() https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java#L350 failed, some error such as NoSuchMethodError or NoClassDefFoundError can not be caught, and pulsar will in abnormal status but no error log will found in the log file.

Modification
modify exception to throwable

Co-authored-by: lamberliu <lamberliu@tencent.com>
(cherry picked from commit f47570322b49e784bd7657c25d54d2755270001a)