Fix flaky test ConnectionTimeoutTest#testLowTimeout. (#15068)
### Motivation

The test `testLowTimeout` fails frequently.  Remove the unused assertion.  
```
org.apache.pulsar.client.impl.ConnectionTimeoutTest ► testLowTimeout
Failed test found in:
  TEST-org.apache.pulsar.client.impl.ConnectionTimeoutTest.xml
Error:
        java.lang.AssertionError: expected [false] but found [true]
```