[Tests] Fix OutOfMemoryError and NoClassDefFoundErrors in tests
- the PulsarByteBufAllocator.DEFAULT instance was replaced in BatchMessageContainerImplTest, but never restored