[state][standalone] When running with more than one function instance, Function instances will crash because of table service throws INTERNAL_SERVER_ERROR
*Motivation*

When running with more than one function instance, Function instances will crash because of table service throws INTERNAL_SERVER_ERROR

```
org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.exceptions.ClientException: fail to access its root range : code = INTERNAL_SERVER_ERROR
        at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.impl.internal.ProtocolInternalUtils.createRootRangeException(ProtocolInternalUtils.java:105) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.impl.internal.RootRangeClientImpl.processCreateNamespaceResponse(RootRangeClientImpl.java:129) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.impl.internal.RootRangeClientImpl.lambda$createNamespace$4(RootRangeClientImpl.java:118) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.utils.RpcUtils$1.onSuccess(RpcUtils.java:78) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.com.google.common.util.concurrent.Futures$4.run(Futures.java:1135) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:655) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:487) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:465) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at org.apache.pulsar.functions.runtime.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[java-instance.jar:2.3.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]

```

in current version of bk, `INTERNAL_SEVER_ERROR` was thrown a client attempts to create a table while the table already exists. In a newer version, the client handles that better.

*Changes*

A temp fix before upgrading BK to 4.9 is to handle creating state tables in a more reliable way.