fix NoClassDefFoundError - io.airlift.compress.lz4.UnsafeUtil (#10983)
* fix NoClassDefFoundError - io.airlift.compress.lz4.UnsafeUtil

Reading a message fails with

[org.apa.pul.cli.imp.ClientCnx] (pulsar-client-io-2-1) [localhost/127.0.0.1:6650] Got exception java.lang.NoClassDefFoundError: Could not initialize class io.airlift.compress.lz4.UnsafeUtil
	at io.airlift.compress.lz4.Lz4RawDecompressor.decompress(Lz4RawDecompressor.java:60)
	at org.apache.pulsar.common.compression.CompressionCodecLZ4.decode(CompressionCodecLZ4.java:91)

* update aircompressor license file

* update aircompressor license file

(cherry picked from commit 2ea1ce66c04ad64d0adc85d21e6e369f0a0f325c)