Fix branch-2.6 build issue (#8335)
### Motivation

Revert jersey version to 2.27 to avoid `java.lang.NoClassDefFoundError: org/apache/pulsar/shade/javax/annotation/Priority` in branch-2.6

(cherry picked from commit 8fc49f177e228b380c5fba6262f46f82fe946857)