[improve][broker] Avoid printing log for IncompatibleSchemaException in ServerCnx (#23938)
### Motivation

If the producer is created with some schema error, the broker will print many error logs like this:

```
ERROR org.apache.pulsar.broker.service.ServerCnx - Try add schema failed, remote address xxx
java.util.concurrent.CompletionException: org.apache.pulsar.broker.service.schema.exceptions.IncompatibleSchemaException: Producers cannot connect or send message without a schema to topics with a schemawhen SchemaValidationEnforced is enabled
```

This error can be reported to the client and not need to print it in the broker.

### Modifications

- Avoid printing log for IncompatibleSchemaException in ServerCnx

(cherry picked from commit 3c0bbee91368086189816c26357491e4fe596e01)