[improve][broker] Close protocol handlers before unloading namespace bundles
### Motivation

When the extensible load manager is configured,
`NamespaceService#unloadNamespaceBundle` could be stuck until 30 seconds
timeout.

```
20:19:13.746 [main:org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateChannelImpl@962] INFO  org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateChannelImpl - localhost:52138 is waiting for owner for serviceUnit:public/__kafka/0xf0000000_0xffffffff
20:19:13.751 [ForkJoinPool.commonPool-worker-3:org.apache.pulsar.broker.resources.MetadataStoreCacheLoader@68] INFO  org.apache.pulsar.broker.resources.MetadataStoreCacheLoader - Successfully updated broker info []
20:19:13.751 [metadata-store-229-1:org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateChannelImpl@447] ERROR org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateChannelImpl - There is no channel owner now.
20:19:13.751 [pulsar-load-manager-222-1:org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateChannelImpl@459] ERROR org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateChannelImpl - Failed to get the channel owner.
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: There is no channel owner now.
20:19:43.750 [CompletableFutureDelayScheduler:org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateChannelImpl@953] WARN  org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateChannelImpl - localhost:52138 failed to wait for owner for serviceUnit:public/__kafka/0xf0000000_0xffffffff; Trying to return the current owner:Optional[localhost:52138]
```

This case happens when there are lookup requests from Pulsar clients,
`Assigning` and `Owned` events will be sent to the service unit channel.
However, during the close of the last broker, the state should be
`Free`. If there are active producers or consumers in the protocol
handler, the state will be changed from `Free` to `Owned` and then
`getActiveOwnerAsync` will be called by `getOwnerAsync`. Since no more
`Owned` events will be written to the channel, the pending request in
`getOwnerRequests` would never be removed.

### Modifications

Close protocol handlers before unloading namespace bundles to ensure no
more lookup requests were sent before the namespaces are unloaded.

Add `PulsarClientBasedHandlerTest` to verify this change works.