[fix][admin] Fix NoClassDefFoundError in the pulsar admin CLI tools
Motivation
https://github.com/apache/pulsar/pull/17158 introduces a new module called `pulsar-client-tools-api`. But this module is not added in the `distribution/shell`. This leads the no class found error when using the pulsar-admin toos.

Modification
* Add dependency `pulsar-client-tools-api` to the `distribution/shell`.

Signed-off-by: Zike Yang <zike@apache.org>