[pulsar-io-elastic-search] Change default document type for compliance with ES 7.x (#4322)
### Motivation

When running Elasticsearch sink on ES 7.0.1, message indexation fails with the following error :

```
- Encountered exception in sink write: 
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=Rejecting mapping update to [geoloc-pulsar] as the final mapping would have more than 1 type: [_doc, doc]]
```

According to https://www.elastic.co/guide/en/elasticsearch/reference/6.3/removal-of-types.html#_schedule_for_removal_of_mapping_types, the recommended document type to use is `_doc`.

### Modifications

Replace document type `doc` with recommended value `_doc`.