[website] fix sidebar (#2241)
### Motivation

In #2237, `administration-auth` is removed. However it is not removed from sidebard. It is causing failures on building website.

```
generate.js triggered...
Error: Improper sidebars.json file, document with id 'administration-auth' not found. Make sure that documents with the ids specified in sidebars.json exist and that no ids are repeated.
    at _loop (/pulsar/site2/website/node_modules/docusaurus/lib/server/readCategories.js:58:17)
    at readCategories (/pulsar/site2/website/node_modules/docusaurus/lib/server/readCategories.js:34:53)
    at DocsSidebar.render (/pulsar/site2/website/node_modules/docusaurus/lib/core/DocsSidebar.js:16:26)
    at processChild (/pulsar/site2/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2204:18)
    at resolve (/pulsar/site2/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
    at ReactDOMServerRenderer.render (/pulsar/site2/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)
    at ReactDOMServerRenderer.read (/pulsar/site2/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2354:19)
    at renderToStaticMarkup (/pulsar/site2/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2737:25)
    at renderToStaticMarkupWithDoctype (/pulsar/site2/website/node_modules/docusaurus/lib/server/renderUtils.js:16:30)
    at /pulsar/site2/website/node_modules/docusaurus/lib/server/generate.js:199:17
```

 ### Changes

Remove `administration-auth` from the sidebar. Also remove codebase page, which doesn't make sense to be there because code changes are happening very frequently. The page quickly becomes out-of-dated.
Additionally cleanup a few things in the sidebar.