Fix java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer when enabling topic metadata compression (#11594)
### Motivation

Related to #11593. This PR is copying the bytes to the DirectBuf to get around issue #11593.

The created issue https://github.com/airlift/aircompressor/issues/133 for tracking fix from [aircompressor](https://github.com/airlift/aircompressor)

### Verifying this change

Make the `ManagedLedgerCompressionTest` running on JDK8

(cherry picked from commit 53c7c13b74fb9c8aecf6680762e889b8b06eb36e)