[Issue 9728] Upgrade GRPC and bookkeeper (#9729)
* Upgraded bookkeeper to 4.13.0; grpc to 1.33

* updated LICENSE

* fixed the rest of the license check

* no idea why license check results on CI are different from local :/

* one more license fix

* Integration tests failed to start container/service there because of java.lang.NoClassDefFoundError: io/perfmark/PerfMark

* another try to get the permark.jar in

* another take on perfmark.jar and integration tests

* add perfmark.jar to LICENSE