Remove python2 from the pulsar images build (#7936)
The pulsar docker and pulsar standalone docker image build failed by:
```
Processing ./pulsar-client/pulsar_client-2.6.0-cp27-cp27mu-manylinux1_x86_64.whl
2020-08-25T02:23:28.9567844Z [INFO] Collecting fastavro
2020-08-25T02:23:29.0080316Z [INFO]   Downloading fastavro-1.0.0.tar.gz (658 kB)
2020-08-25T02:23:29.3108074Z [INFO]     ERROR: Command errored out with exit status 1:
2020-08-25T02:23:29.3109489Z [INFO]      command: /usr/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jvZueR/fastavro/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jvZueR/fastavro/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-iH1mMy
2020-08-25T02:23:29.3110061Z [INFO]          cwd: /tmp/pip-install-jvZueR/fastavro/
2020-08-25T02:23:29.3110303Z [INFO]     Complete output (5 lines):
2020-08-25T02:23:29.3110520Z [INFO]     Traceback (most recent call last):
2020-08-25T02:23:29.3110741Z [INFO]       File "<string>", line 1, in <module>
2020-08-25T02:23:29.3111190Z [INFO]       File "/tmp/pip-install-jvZueR/fastavro/setup.py", line 58, in <module>
2020-08-25T02:23:29.3111437Z [INFO]         if sys.implementation.name != "pypy":
2020-08-25T02:23:29.3111886Z [INFO]     AttributeError: 'module' object has no attribute 'implementation'
```

I remove the python2.7 and using the python3 to build images.

* Remove python2 in images

* Remove python2 stuff

* Update the default python version

(cherry picked from commit ed356add3bf5194058854b2fdccc739be6d697c6)