[improve][broker] Don't print error logs for ProducerBusyException (#23929)
### Motivation

When the producer's maximum count is reached, the broker will log the following error message:
```
2025-02-05T18:31:37,996+0800 [pulsar-io-18-16] ERROR org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:57684] Failed to create topic persistent://public/default/test2asgasgaw, producerId=1
java.util.concurrent.CompletionException: org.apache.pulsar.broker.service.BrokerServiceException$ProducerBusyException: Topic 'persistent://public/default/test2asgasgaw' reached max producers limit
```

These errors are related to the client side. The client can handle the error, so we don't need to print it in the broker log.

### Modifications

- Avoid printing the error log for the ProducerBusyException

(cherry picked from commit 144fe2eb634471d338a7e6ee879bc6175e5d061c)