[improve][dependency] Remove jul-to-slf4j (#16320)
### Motivation

see also https://lists.apache.org/thread/65skwo492w2nfjwhb3d9y51roq13h8bs

PulsarAdminImpl has a static block requires classpath contains exact either of:

* slf4j-jdk14
* jul-to-slf4j

It causes an issue that if user depends on neither slf4j-jdk14 nor jul-to-slf4j, PulsarAdminImpl will panic with NoClassDefFoundError. And thus, user should add one of them (basically jul-to-slf4j) even if they don't depend on it effectively.

### Modifications

Remove jul-to-slf4j from all modules under Pulsar.

The Pulsar project uses slf4j as the logging facade consistently. If a user want to add a dependency using a different logging framework, they should take care of the packaging strategy themselves.

pulsar-sql has a dependency to slf4j-jdk14 which redirect slf4j to jul. Since this is a unidirectional redirection, it won't cause runtime error, but pulsar-sql will logging with jul framework, which is the same as with previous workaround.