Add command for generate directory documents (#6015)
### Motivation

Because the directory documents not create, throw the exception:

```
+ ./pulsar-admin-doc-gen.sh
./pulsar-admin-doc-gen.sh: line 28: /pulsar/site2/website/brodocs/documents/broker-stats.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 29: /pulsar/site2/website/brodocs/documents/brokers.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 30: /pulsar/site2/website/brodocs/documents/clusters.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 31: /pulsar/site2/website/brodocs/documents/functions.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 32: /pulsar/site2/website/brodocs/documents/namespaces.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 33: /pulsar/site2/website/brodocs/documents/ns-isolation-policy.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 34: /pulsar/site2/website/brodocs/documents/sources.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 35: /pulsar/site2/website/brodocs/documents/sinks.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 36: /pulsar/site2/website/brodocs/documents/topics.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 37: /pulsar/site2/website/brodocs/documents/tenants.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 38: /pulsar/site2/website/brodocs/documents/resource-quotas.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 39: /pulsar/site2/website/brodocs/documents/schemas.md: No such file or directory
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'marked'
```

### Modifications

* Add command for creating the directory

### Verifying this change

local pass