[Integeration-test]Fix integration-test failed when execute pip3 install pulsar_client (#4754)
* ### Motivation
When installing the pulsar-client-2.5.0 using the image openjdk:8-jdk-slim, for debian 10 systems, python3.7 will be installed when apt-get install python3 is executed. When installing the client using pip3, the following exception will be thrown
```
cat /etc/issue
Debian GNU/Linux 10 \n \l

root@40fdedf3f3c3:/# python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

root@40fdedf3f3c3:/# pip3 install pulsar_client-2.5.0-cp35-cp35m-manylinux1_x86_64.whl
ERROR: pulsar_client-2.5.0-cp35-cp35m-manylinux1_x86_64.whl is not a supported wheel on this platform.
```

### Modifications

Install Use pip3.5 instead of pip3.

* Deleute no used tools

* Fix Docker command