[Hotfix][Docs]Fixed document missing original (#10679)
https://github.com/apache/pulsar/runs/2644824512?check_suite_focus=true
```
Error: No 'original_id' field found in /pulsar/site2/website/versioned_docs/version-2.7.2/deploy-bare-metal-multi-cluster.md. Perhaps you forgot to add it when importing prior versions of your docs?
    at forEach (/pulsar/site2/website/node_modules/docusaurus/lib/server/versionFallback.js:64:11)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/pulsar/site2/website/node_modules/docusaurus/lib/server/versionFallback.js:52:7)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module._compile (/pulsar/site2/website/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/pulsar/site2/website/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```